{% set name = "flytekitplugins-athena" %}
{% set version = "1.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-athena-{{ version }}.tar.gz
  sha256: dd3ce1adf080e84fd008eafad2cdb62615781913dc78df460d554bd81a2f054e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - flytekit >=1.0.0b3,<1.2.0

test:
  imports:
    - flytekitplugins.athena
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/flytekitplugins-athena/
  summary: This package holds the Athena plugins for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Athena plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-athena/](https://pypi.org/project/flytekitplugins-athena/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-aws-athena

extra:
  recipe-maintainers:
    - sugatoray
